export const TYPES = {
    PrismaClient: Symbol.for("PrismaClient"),
    EmployeeRepository: Symbol.for("EmployeeRepository"),
    EmployeeService: Symbol.for("EmployeeService"),
    EmployeeController: Symbol.for("EmployeeController"),
    UserRepository: Symbol.for("UserRepository"),
    UserService: Symbol.for("UserService"),
    UserController: Symbol.for("UserController"),
    AuthService: Symbol.for("AuthService"),
    AuthController: Symbol.for("AuthController"),
    TeamRepository: Symbol.for("TeamRepository"),
    TeamService: Symbol.for("TeamService"),
    TeamController: Symbol.for("TeamController"),
    PolicyRepository: Symbol.for("PolicyRepository"),
    PolicyService: Symbol.for("PolicyService"),
    PolicyController: Symbol.for("PolicyController"),
};
